export const posts = [
    {
      title: "second blog lolz!",
      description: "obvious",
      date: "October 1st 2024",
      author: "IdealistCat",
      tags: ["tester"],
      blog: ["IMAGE!??!?!?!?!?"],
      img_url: "blogStuff/testerImage",
    },
    {
      title: "second blog lolz!",
      description: "obvious",
      date: "October 1st 2024",
      author: "IdealistCat",
      tags: ["unserious", "tester"],
      blog: [
        "fucking around and finding out at its finest lol",
        "fucking lorem and finding out at its finest lol",
        "fucking around and ipsum out at its finest lol",
        "deiet around and finding out at its finest lol",
        "fucking around and finding amet at its finest lol",
        "defenitely got that wrong.",
      ],
      img_url: undefined,
    },
    {
      title: "first blog lolz!",
      description: "obvious",
      date: "October 1st 2024",
      author: "IdealistCat",
      tags: ["unserious", "fpotm", "teset"], // fpotm = first post of the month
      blog: [
        "hello!!",
        "why did i do this you are most likely asking.",
        "Idk!",
        "I have a cripling addiction to find an excuse for more web coding",
        "LOL!",
      ],
      img_url: undefined,
    },
  ];var posts = [
  {
    title: "second blog lolz!",
    description: "obvious",
    date: "October 1st 2024",
    author: "IdealistCat",
    tags: ["tester"],
    blog: ["IMAGE!??!?!?!?!?"],
    img_url: "blogStuff/testerImage",
  },
  {
    title: "second blog lolz!",
    description: "obvious",
    date: "October 1st 2024",
    author: "IdealistCat",
    tags: ["unserious", "tester"],
    blog: [
      "fucking around and finding out at its finest lol",
      "fucking lorem and finding out at its finest lol",
      "fucking around and ipsum out at its finest lol",
      "deiet around and finding out at its finest lol",
      "fucking around and finding amet at its finest lol",
      "defenitely got that wrong.",
    ],
    img_url: undefined,
  },
  {
    title: "first blog lolz!",
    description: "obvious",
    date: "October 1st 2024",
    author: "IdealistCat",
    tags: ["unserious", "fpotm", "teset"], // fpotm = first post of the month
    blog: [
      "hello!!",
      "why did i do this you are most likely asking.",
      "Idk!",
      "I have a cripling addiction to find an excuse for more web coding",
      "LOL!",
    ],
    img_url: undefined,
  },
];